version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: bookingpass
      POSTGRES_DB: bookingdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: booking_redis
    restart: always
    ports:
      - "6379:6379"
